<?php

/**
 * @file
 * dp_html stuff.
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\dp_html\Controller\HtmlPageController;

/**
 * Implements hook_preprocess_node().
 */
function dp_html_preprocess_node(&$variables) {
  $node = $variables['node'];
  $html_controller = new HtmlPageController();
  if ($node->bundle() == 'page' && $node->isPublished()) {
    $config = \Drupal::config('doc.adminsettings');
    switch (strtolower($node->label())) {
      case 'terms of use' :
        $url = $config->get('tsandcs_url');
        if (isset($url) && $url !== '' && UrlHelper::isValid($url) !== FALSE) {
          $html = $html_controller->content($url);
          $variables['content']['body'] = $html;
        }
        break;
      case 'privacy policy' :
        $url = $config->get('privacy_url');
        if (isset($url) && $url !== '' && UrlHelper::isValid($url) !== FALSE) {
          $html = $html_controller->content($url);
          $variables['content']['body'] = $html;
        }
        break;
    }
  }
}
